version: '3.8'

services:
  # NestJS API Server (uses external AWS RDS & Redis)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nova-hr-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - nova-hr-network
    volumes:
      - ./apps/api/uploads:/app/uploads

  # MinIO for file storage
  minio:
    image: minio/minio:latest
    container_name: nova-hr-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-nova_hr_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-NovaHR2024!MinIOPass_AWS}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - nova-hr-network
    command: server /data --console-address ":9001"

networks:
  nova-hr-network:
    driver: bridge

volumes:
  minio_data:
    driver: local