packages:
  - 'apps/*'
  - 'packages/*'

# Shared dependencies hoisting
shared-workspace-lockfile: true
link-workspace-packages: true
prefer-workspace-packages: true

# Peer dependencies auto-install
auto-install-peers: true